export const primitiveTypes: [
  type: string,
  realType: string,
  dependencies: string[]
][] = [
  ["char", "char", []],
  ["schar", "signed char", []],
  ["short", "signed short", []],
  ["int", "signed int", []],
  ["long", "signed long", []],
  ["longlong", "signed long long", []],
  ["uchar", "unsigned char", []],
  ["ushort", "unsigned short", []],
  ["uint", "unsigned int", []],
  ["ulong", "unsigned long", []],
  ["ulonglong", "unsigned long long", []],
  ["float", "float", []],
  ["double", "double", []],
  ["long_double", "long double", []],
  ["size", "size_t", ["<stddef.h>"]],
  ["ptrdiff", "ptrdiff_t", ["<stddef.h>"]],
  ["i8", "int8_t", ["<stdint.h>"]],
  ["i16", "int16_t", ["<stdint.h>"]],
  ["i32", "int32_t", ["<stdint.h>"]],
  ["i64", "int64_t", ["<stdint.h>"]],
  ["i8fast", "int_fast8_t", ["<stdint.h>"]],
  ["i16fast", "int_fast16_t", ["<stdint.h>"]],
  ["i32fast", "int_fast32_t", ["<stdint.h>"]],
  ["i64fast", "int_fast64_t", ["<stdint.h>"]],
  ["i8least", "int_least8_t", ["<stdint.h>"]],
  ["i16least", "int_least16_t", ["<stdint.h>"]],
  ["i32least", "int_least32_t", ["<stdint.h>"]],
  ["i64least", "int_least64_t", ["<stdint.h>"]],
  ["iptr", "intptr_t", ["<stdint.h>"]],
  ["imax", "intmax_t", ["<stdint.h>"]],
  ["u8", "uint8_t", ["<stdint.h>"]],
  ["u16", "uint16_t", ["<stdint.h>"]],
  ["u32", "uint32_t", ["<stdint.h>"]],
  ["u64", "uint64_t", ["<stdint.h>"]],
  ["u8fast", "uint_fast8_t", ["<stdint.h>"]],
  ["u16fast", "uint_fast16_t", ["<stdint.h>"]],
  ["u32fast", "uint_fast32_t", ["<stdint.h>"]],
  ["u64fast", "uint_fast64_t", ["<stdint.h>"]],
  ["u8least", "uint_least8_t", ["<stdint.h>"]],
  ["u16least", "uint_least16_t", ["<stdint.h>"]],
  ["u32least", "uint_least32_t", ["<stdint.h>"]],
  ["u64least", "uint_least64_t", ["<stdint.h>"]],
  ["uptr", "uintptr_t", ["<stdint.h>"]],
  ["umax", "uintmax_t", ["<stdint.h>"]],
  ["bool", "bool", ["<stdbool.h>"]],
];
