/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   fake_file_name (file name is useless too)          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: 42header-remover <whatever@example.com>    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 1970/01/01 00:00:00 by VCS handles       #+#    #+#             */
/*   Updated: 1970/01/01 00:00:00 by file history     ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef FT_TYPES_DERIVED_H
# define FT_TYPES_DERIVED_H

# include "ft_types.h"

typedef t_c		*t_pc;
typedef t_c		(*t_func_c_p)(void *context);
typedef t_c		*(*t_func_pc_p)(void *context);
typedef t_c		(*t_func_c_c_p)(t_c v, t_p c);
typedef t_pc	(*t_func_pc_c_p)(t_c v, t_p c);
typedef t_c		(*t_func_c_pc_p)(t_pc v, t_p c);
typedef t_pc	(*t_func_pc_pc_p)(t_pc v, t_p c);
typedef t_hhd	*t_phhd;
typedef t_hhd	(*t_func_hhd_p)(void *context);
typedef t_hhd	*(*t_func_phhd_p)(void *context);
typedef t_hhd	(*t_func_hhd_hhd_p)(t_hhd v, t_p c);
typedef t_phhd	(*t_func_phhd_hhd_p)(t_hhd v, t_p c);
typedef t_hhd	(*t_func_hhd_phhd_p)(t_phhd v, t_p c);
typedef t_phhd	(*t_func_phhd_phhd_p)(t_phhd v, t_p c);
typedef t_hd	*t_phd;
typedef t_hd	(*t_func_hd_p)(void *context);
typedef t_hd	*(*t_func_phd_p)(void *context);
typedef t_hd	(*t_func_hd_hd_p)(t_hd v, t_p c);
typedef t_phd	(*t_func_phd_hd_p)(t_hd v, t_p c);
typedef t_hd	(*t_func_hd_phd_p)(t_phd v, t_p c);
typedef t_phd	(*t_func_phd_phd_p)(t_phd v, t_p c);
typedef t_d		*t_pd;
typedef t_d		(*t_func_d_p)(void *context);
typedef t_d		*(*t_func_pd_p)(void *context);
typedef t_d		(*t_func_d_d_p)(t_d v, t_p c);
typedef t_pd	(*t_func_pd_d_p)(t_d v, t_p c);
typedef t_d		(*t_func_d_pd_p)(t_pd v, t_p c);
typedef t_pd	(*t_func_pd_pd_p)(t_pd v, t_p c);
typedef t_ld	*t_pld;
typedef t_ld	(*t_func_ld_p)(void *context);
typedef t_ld	*(*t_func_pld_p)(void *context);
typedef t_ld	(*t_func_ld_ld_p)(t_ld v, t_p c);
typedef t_pld	(*t_func_pld_ld_p)(t_ld v, t_p c);
typedef t_ld	(*t_func_ld_pld_p)(t_pld v, t_p c);
typedef t_pld	(*t_func_pld_pld_p)(t_pld v, t_p c);
typedef t_lld	*t_plld;
typedef t_lld	(*t_func_lld_p)(void *context);
typedef t_lld	*(*t_func_plld_p)(void *context);
typedef t_lld	(*t_func_lld_lld_p)(t_lld v, t_p c);
typedef t_plld	(*t_func_plld_lld_p)(t_lld v, t_p c);
typedef t_lld	(*t_func_lld_plld_p)(t_plld v, t_p c);
typedef t_plld	(*t_func_plld_plld_p)(t_plld v, t_p c);
typedef t_hhu	*t_phhu;
typedef t_hhu	(*t_func_hhu_p)(void *context);
typedef t_hhu	*(*t_func_phhu_p)(void *context);
typedef t_hhu	(*t_func_hhu_hhu_p)(t_hhu v, t_p c);
typedef t_phhu	(*t_func_phhu_hhu_p)(t_hhu v, t_p c);
typedef t_hhu	(*t_func_hhu_phhu_p)(t_phhu v, t_p c);
typedef t_phhu	(*t_func_phhu_phhu_p)(t_phhu v, t_p c);
typedef t_hu	*t_phu;
typedef t_hu	(*t_func_hu_p)(void *context);
typedef t_hu	*(*t_func_phu_p)(void *context);
typedef t_hu	(*t_func_hu_hu_p)(t_hu v, t_p c);
typedef t_phu	(*t_func_phu_hu_p)(t_hu v, t_p c);
typedef t_hu	(*t_func_hu_phu_p)(t_phu v, t_p c);
typedef t_phu	(*t_func_phu_phu_p)(t_phu v, t_p c);
typedef t_u		*t_pu;
typedef t_u		(*t_func_u_p)(void *context);
typedef t_u		*(*t_func_pu_p)(void *context);
typedef t_u		(*t_func_u_u_p)(t_u v, t_p c);
typedef t_pu	(*t_func_pu_u_p)(t_u v, t_p c);
typedef t_u		(*t_func_u_pu_p)(t_pu v, t_p c);
typedef t_pu	(*t_func_pu_pu_p)(t_pu v, t_p c);
typedef t_lu	*t_plu;
typedef t_lu	(*t_func_lu_p)(void *context);
typedef t_lu	*(*t_func_plu_p)(void *context);
typedef t_lu	(*t_func_lu_lu_p)(t_lu v, t_p c);
typedef t_plu	(*t_func_plu_lu_p)(t_lu v, t_p c);
typedef t_lu	(*t_func_lu_plu_p)(t_plu v, t_p c);
typedef t_plu	(*t_func_plu_plu_p)(t_plu v, t_p c);
typedef t_llu	*t_pllu;
typedef t_llu	(*t_func_llu_p)(void *context);
typedef t_llu	*(*t_func_pllu_p)(void *context);
typedef t_llu	(*t_func_llu_llu_p)(t_llu v, t_p c);
typedef t_pllu	(*t_func_pllu_llu_p)(t_llu v, t_p c);
typedef t_llu	(*t_func_llu_pllu_p)(t_pllu v, t_p c);
typedef t_pllu	(*t_func_pllu_pllu_p)(t_pllu v, t_p c);
typedef t_f		*t_pf;
typedef t_f		(*t_func_f_p)(void *context);
typedef t_f		*(*t_func_pf_p)(void *context);
typedef t_f		(*t_func_f_f_p)(t_f v, t_p c);
typedef t_pf	(*t_func_pf_f_p)(t_f v, t_p c);
typedef t_f		(*t_func_f_pf_p)(t_pf v, t_p c);
typedef t_pf	(*t_func_pf_pf_p)(t_pf v, t_p c);
typedef t_lf	*t_plf;
typedef t_lf	(*t_func_lf_p)(void *context);
typedef t_lf	*(*t_func_plf_p)(void *context);
typedef t_lf	(*t_func_lf_lf_p)(t_lf v, t_p c);
typedef t_plf	(*t_func_plf_lf_p)(t_lf v, t_p c);
typedef t_lf	(*t_func_lf_plf_p)(t_plf v, t_p c);
typedef t_plf	(*t_func_plf_plf_p)(t_plf v, t_p c);
typedef t_llf	*t_pllf;
typedef t_llf	(*t_func_llf_p)(void *context);
typedef t_llf	*(*t_func_pllf_p)(void *context);
typedef t_llf	(*t_func_llf_llf_p)(t_llf v, t_p c);
typedef t_pllf	(*t_func_pllf_llf_p)(t_llf v, t_p c);
typedef t_llf	(*t_func_llf_pllf_p)(t_pllf v, t_p c);
typedef t_pllf	(*t_func_pllf_pllf_p)(t_pllf v, t_p c);
typedef t_td	*t_ptd;
typedef t_td	(*t_func_td_p)(void *context);
typedef t_td	*(*t_func_ptd_p)(void *context);
typedef t_td	(*t_func_td_td_p)(t_td v, t_p c);
typedef t_ptd	(*t_func_ptd_td_p)(t_td v, t_p c);
typedef t_td	(*t_func_td_ptd_p)(t_ptd v, t_p c);
typedef t_ptd	(*t_func_ptd_ptd_p)(t_ptd v, t_p c);
typedef t_zu	*t_pzu;
typedef t_zu	(*t_func_zu_p)(void *context);
typedef t_zu	*(*t_func_pzu_p)(void *context);
typedef t_zu	(*t_func_zu_zu_p)(t_zu v, t_p c);
typedef t_pzu	(*t_func_pzu_zu_p)(t_zu v, t_p c);
typedef t_zu	(*t_func_zu_pzu_p)(t_pzu v, t_p c);
typedef t_pzu	(*t_func_pzu_pzu_p)(t_pzu v, t_p c);
typedef t_jd	*t_pjd;
typedef t_jd	(*t_func_jd_p)(void *context);
typedef t_jd	*(*t_func_pjd_p)(void *context);
typedef t_jd	(*t_func_jd_jd_p)(t_jd v, t_p c);
typedef t_pjd	(*t_func_pjd_jd_p)(t_jd v, t_p c);
typedef t_jd	(*t_func_jd_pjd_p)(t_pjd v, t_p c);
typedef t_pjd	(*t_func_pjd_pjd_p)(t_pjd v, t_p c);
typedef t_ju	*t_pju;
typedef t_ju	(*t_func_ju_p)(void *context);
typedef t_ju	*(*t_func_pju_p)(void *context);
typedef t_ju	(*t_func_ju_ju_p)(t_ju v, t_p c);
typedef t_pju	(*t_func_pju_ju_p)(t_ju v, t_p c);
typedef t_ju	(*t_func_ju_pju_p)(t_pju v, t_p c);
typedef t_pju	(*t_func_pju_pju_p)(t_pju v, t_p c);
typedef t_i8	*t_pi8;
typedef t_i8	(*t_func_i8_p)(void *context);
typedef t_i8	*(*t_func_pi8_p)(void *context);
typedef t_i8	(*t_func_i8_i8_p)(t_i8 v, t_p c);
typedef t_pi8	(*t_func_pi8_i8_p)(t_i8 v, t_p c);
typedef t_i8	(*t_func_i8_pi8_p)(t_pi8 v, t_p c);
typedef t_pi8	(*t_func_pi8_pi8_p)(t_pi8 v, t_p c);
typedef t_i16	*t_pi16;
typedef t_i16	(*t_func_i16_p)(void *context);
typedef t_i16	*(*t_func_pi16_p)(void *context);
typedef t_i16	(*t_func_i16_i16_p)(t_i16 v, t_p c);
typedef t_pi16	(*t_func_pi16_i16_p)(t_i16 v, t_p c);
typedef t_i16	(*t_func_i16_pi16_p)(t_pi16 v, t_p c);
typedef t_pi16	(*t_func_pi16_pi16_p)(t_pi16 v, t_p c);
typedef t_i32	*t_pi32;
typedef t_i32	(*t_func_i32_p)(void *context);
typedef t_i32	*(*t_func_pi32_p)(void *context);
typedef t_i32	(*t_func_i32_i32_p)(t_i32 v, t_p c);
typedef t_pi32	(*t_func_pi32_i32_p)(t_i32 v, t_p c);
typedef t_i32	(*t_func_i32_pi32_p)(t_pi32 v, t_p c);
typedef t_pi32	(*t_func_pi32_pi32_p)(t_pi32 v, t_p c);
typedef t_i64	*t_pi64;
typedef t_i64	(*t_func_i64_p)(void *context);
typedef t_i64	*(*t_func_pi64_p)(void *context);
typedef t_i64	(*t_func_i64_i64_p)(t_i64 v, t_p c);
typedef t_pi64	(*t_func_pi64_i64_p)(t_i64 v, t_p c);
typedef t_i64	(*t_func_i64_pi64_p)(t_pi64 v, t_p c);
typedef t_pi64	(*t_func_pi64_pi64_p)(t_pi64 v, t_p c);
typedef t_u8	*t_pu8;
typedef t_u8	(*t_func_u8_p)(void *context);
typedef t_u8	*(*t_func_pu8_p)(void *context);
typedef t_u8	(*t_func_u8_u8_p)(t_u8 v, t_p c);
typedef t_pu8	(*t_func_pu8_u8_p)(t_u8 v, t_p c);
typedef t_u8	(*t_func_u8_pu8_p)(t_pu8 v, t_p c);
typedef t_pu8	(*t_func_pu8_pu8_p)(t_pu8 v, t_p c);
typedef t_u16	*t_pu16;
typedef t_u16	(*t_func_u16_p)(void *context);
typedef t_u16	*(*t_func_pu16_p)(void *context);
typedef t_u16	(*t_func_u16_u16_p)(t_u16 v, t_p c);
typedef t_pu16	(*t_func_pu16_u16_p)(t_u16 v, t_p c);
typedef t_u16	(*t_func_u16_pu16_p)(t_pu16 v, t_p c);
typedef t_pu16	(*t_func_pu16_pu16_p)(t_pu16 v, t_p c);
typedef t_u32	*t_pu32;
typedef t_u32	(*t_func_u32_p)(void *context);
typedef t_u32	*(*t_func_pu32_p)(void *context);
typedef t_u32	(*t_func_u32_u32_p)(t_u32 v, t_p c);
typedef t_pu32	(*t_func_pu32_u32_p)(t_u32 v, t_p c);
typedef t_u32	(*t_func_u32_pu32_p)(t_pu32 v, t_p c);
typedef t_pu32	(*t_func_pu32_pu32_p)(t_pu32 v, t_p c);
typedef t_u64	*t_pu64;
typedef t_u64	(*t_func_u64_p)(void *context);
typedef t_u64	*(*t_func_pu64_p)(void *context);
typedef t_u64	(*t_func_u64_u64_p)(t_u64 v, t_p c);
typedef t_pu64	(*t_func_pu64_u64_p)(t_u64 v, t_p c);
typedef t_u64	(*t_func_u64_pu64_p)(t_pu64 v, t_p c);
typedef t_pu64	(*t_func_pu64_pu64_p)(t_pu64 v, t_p c);
typedef t_i8f	*t_pi8f;
typedef t_i8f	(*t_func_i8f_p)(void *context);
typedef t_i8f	*(*t_func_pi8f_p)(void *context);
typedef t_i8f	(*t_func_i8f_i8f_p)(t_i8f v, t_p c);
typedef t_pi8f	(*t_func_pi8f_i8f_p)(t_i8f v, t_p c);
typedef t_i8f	(*t_func_i8f_pi8f_p)(t_pi8f v, t_p c);
typedef t_pi8f	(*t_func_pi8f_pi8f_p)(t_pi8f v, t_p c);
typedef t_i16f	*t_pi16f;
typedef t_i16f	(*t_func_i16f_p)(void *context);
typedef t_i16f	*(*t_func_pi16f_p)(void *context);
typedef t_i16f	(*t_func_i16f_i16f_p)(t_i16f v, t_p c);
typedef t_pi16f	(*t_func_pi16f_i16f_p)(t_i16f v, t_p c);
typedef t_i16f	(*t_func_i16f_pi16f_p)(t_pi16f v, t_p c);
typedef t_pi16f	(*t_func_pi16f_pi16f_p)(t_pi16f v, t_p c);
typedef t_i32f	*t_pi32f;
typedef t_i32f	(*t_func_i32f_p)(void *context);
typedef t_i32f	*(*t_func_pi32f_p)(void *context);
typedef t_i32f	(*t_func_i32f_i32f_p)(t_i32f v, t_p c);
typedef t_pi32f	(*t_func_pi32f_i32f_p)(t_i32f v, t_p c);
typedef t_i32f	(*t_func_i32f_pi32f_p)(t_pi32f v, t_p c);
typedef t_pi32f	(*t_func_pi32f_pi32f_p)(t_pi32f v, t_p c);
typedef t_i64f	*t_pi64f;
typedef t_i64f	(*t_func_i64f_p)(void *context);
typedef t_i64f	*(*t_func_pi64f_p)(void *context);
typedef t_i64f	(*t_func_i64f_i64f_p)(t_i64f v, t_p c);
typedef t_pi64f	(*t_func_pi64f_i64f_p)(t_i64f v, t_p c);
typedef t_i64f	(*t_func_i64f_pi64f_p)(t_pi64f v, t_p c);
typedef t_pi64f	(*t_func_pi64f_pi64f_p)(t_pi64f v, t_p c);
typedef t_u8f	*t_pu8f;
typedef t_u8f	(*t_func_u8f_p)(void *context);
typedef t_u8f	*(*t_func_pu8f_p)(void *context);
typedef t_u8f	(*t_func_u8f_u8f_p)(t_u8f v, t_p c);
typedef t_pu8f	(*t_func_pu8f_u8f_p)(t_u8f v, t_p c);
typedef t_u8f	(*t_func_u8f_pu8f_p)(t_pu8f v, t_p c);
typedef t_pu8f	(*t_func_pu8f_pu8f_p)(t_pu8f v, t_p c);
typedef t_u16f	*t_pu16f;
typedef t_u16f	(*t_func_u16f_p)(void *context);
typedef t_u16f	*(*t_func_pu16f_p)(void *context);
typedef t_u16f	(*t_func_u16f_u16f_p)(t_u16f v, t_p c);
typedef t_pu16f	(*t_func_pu16f_u16f_p)(t_u16f v, t_p c);
typedef t_u16f	(*t_func_u16f_pu16f_p)(t_pu16f v, t_p c);
typedef t_pu16f	(*t_func_pu16f_pu16f_p)(t_pu16f v, t_p c);
typedef t_u32f	*t_pu32f;
typedef t_u32f	(*t_func_u32f_p)(void *context);
typedef t_u32f	*(*t_func_pu32f_p)(void *context);
typedef t_u32f	(*t_func_u32f_u32f_p)(t_u32f v, t_p c);
typedef t_pu32f	(*t_func_pu32f_u32f_p)(t_u32f v, t_p c);
typedef t_u32f	(*t_func_u32f_pu32f_p)(t_pu32f v, t_p c);
typedef t_pu32f	(*t_func_pu32f_pu32f_p)(t_pu32f v, t_p c);
typedef t_u64f	*t_pu64f;
typedef t_u64f	(*t_func_u64f_p)(void *context);
typedef t_u64f	*(*t_func_pu64f_p)(void *context);
typedef t_u64f	(*t_func_u64f_u64f_p)(t_u64f v, t_p c);
typedef t_pu64f	(*t_func_pu64f_u64f_p)(t_u64f v, t_p c);
typedef t_u64f	(*t_func_u64f_pu64f_p)(t_pu64f v, t_p c);
typedef t_pu64f	(*t_func_pu64f_pu64f_p)(t_pu64f v, t_p c);
typedef t_i8l	*t_pi8l;
typedef t_i8l	(*t_func_i8l_p)(void *context);
typedef t_i8l	*(*t_func_pi8l_p)(void *context);
typedef t_i8l	(*t_func_i8l_i8l_p)(t_i8l v, t_p c);
typedef t_pi8l	(*t_func_pi8l_i8l_p)(t_i8l v, t_p c);
typedef t_i8l	(*t_func_i8l_pi8l_p)(t_pi8l v, t_p c);
typedef t_pi8l	(*t_func_pi8l_pi8l_p)(t_pi8l v, t_p c);
typedef t_i16l	*t_pi16l;
typedef t_i16l	(*t_func_i16l_p)(void *context);
typedef t_i16l	*(*t_func_pi16l_p)(void *context);
typedef t_i16l	(*t_func_i16l_i16l_p)(t_i16l v, t_p c);
typedef t_pi16l	(*t_func_pi16l_i16l_p)(t_i16l v, t_p c);
typedef t_i16l	(*t_func_i16l_pi16l_p)(t_pi16l v, t_p c);
typedef t_pi16l	(*t_func_pi16l_pi16l_p)(t_pi16l v, t_p c);
typedef t_i32l	*t_pi32l;
typedef t_i32l	(*t_func_i32l_p)(void *context);
typedef t_i32l	*(*t_func_pi32l_p)(void *context);
typedef t_i32l	(*t_func_i32l_i32l_p)(t_i32l v, t_p c);
typedef t_pi32l	(*t_func_pi32l_i32l_p)(t_i32l v, t_p c);
typedef t_i32l	(*t_func_i32l_pi32l_p)(t_pi32l v, t_p c);
typedef t_pi32l	(*t_func_pi32l_pi32l_p)(t_pi32l v, t_p c);
typedef t_i64l	*t_pi64l;
typedef t_i64l	(*t_func_i64l_p)(void *context);
typedef t_i64l	*(*t_func_pi64l_p)(void *context);
typedef t_i64l	(*t_func_i64l_i64l_p)(t_i64l v, t_p c);
typedef t_pi64l	(*t_func_pi64l_i64l_p)(t_i64l v, t_p c);
typedef t_i64l	(*t_func_i64l_pi64l_p)(t_pi64l v, t_p c);
typedef t_pi64l	(*t_func_pi64l_pi64l_p)(t_pi64l v, t_p c);
typedef t_u8l	*t_pu8l;
typedef t_u8l	(*t_func_u8l_p)(void *context);
typedef t_u8l	*(*t_func_pu8l_p)(void *context);
typedef t_u8l	(*t_func_u8l_u8l_p)(t_u8l v, t_p c);
typedef t_pu8l	(*t_func_pu8l_u8l_p)(t_u8l v, t_p c);
typedef t_u8l	(*t_func_u8l_pu8l_p)(t_pu8l v, t_p c);
typedef t_pu8l	(*t_func_pu8l_pu8l_p)(t_pu8l v, t_p c);
typedef t_u16l	*t_pu16l;
typedef t_u16l	(*t_func_u16l_p)(void *context);
typedef t_u16l	*(*t_func_pu16l_p)(void *context);
typedef t_u16l	(*t_func_u16l_u16l_p)(t_u16l v, t_p c);
typedef t_pu16l	(*t_func_pu16l_u16l_p)(t_u16l v, t_p c);
typedef t_u16l	(*t_func_u16l_pu16l_p)(t_pu16l v, t_p c);
typedef t_pu16l	(*t_func_pu16l_pu16l_p)(t_pu16l v, t_p c);
typedef t_u32l	*t_pu32l;
typedef t_u32l	(*t_func_u32l_p)(void *context);
typedef t_u32l	*(*t_func_pu32l_p)(void *context);
typedef t_u32l	(*t_func_u32l_u32l_p)(t_u32l v, t_p c);
typedef t_pu32l	(*t_func_pu32l_u32l_p)(t_u32l v, t_p c);
typedef t_u32l	(*t_func_u32l_pu32l_p)(t_pu32l v, t_p c);
typedef t_pu32l	(*t_func_pu32l_pu32l_p)(t_pu32l v, t_p c);
typedef t_u64l	*t_pu64l;
typedef t_u64l	(*t_func_u64l_p)(void *context);
typedef t_u64l	*(*t_func_pu64l_p)(void *context);
typedef t_u64l	(*t_func_u64l_u64l_p)(t_u64l v, t_p c);
typedef t_pu64l	(*t_func_pu64l_u64l_p)(t_u64l v, t_p c);
typedef t_u64l	(*t_func_u64l_pu64l_p)(t_pu64l v, t_p c);
typedef t_pu64l	(*t_func_pu64l_pu64l_p)(t_pu64l v, t_p c);
typedef t_imax	*t_pimax;
typedef t_imax	(*t_func_imax_p)(void *context);
typedef t_imax	*(*t_func_pimax_p)(void *context);
typedef t_imax	(*t_func_imax_imax_p)(t_imax v, t_p c);
typedef t_pimax	(*t_func_pimax_imax_p)(t_imax v, t_p c);
typedef t_imax	(*t_func_imax_pimax_p)(t_pimax v, t_p c);
typedef t_pimax	(*t_func_pimax_pimax_p)(t_pimax v, t_p c);
typedef t_iptr	*t_piptr;
typedef t_iptr	(*t_func_iptr_p)(void *context);
typedef t_iptr	*(*t_func_piptr_p)(void *context);
typedef t_iptr	(*t_func_iptr_iptr_p)(t_iptr v, t_p c);
typedef t_piptr	(*t_func_piptr_iptr_p)(t_iptr v, t_p c);
typedef t_iptr	(*t_func_iptr_piptr_p)(t_piptr v, t_p c);
typedef t_piptr	(*t_func_piptr_piptr_p)(t_piptr v, t_p c);
typedef t_umax	*t_pumax;
typedef t_umax	(*t_func_umax_p)(void *context);
typedef t_umax	*(*t_func_pumax_p)(void *context);
typedef t_umax	(*t_func_umax_umax_p)(t_umax v, t_p c);
typedef t_pumax	(*t_func_pumax_umax_p)(t_umax v, t_p c);
typedef t_umax	(*t_func_umax_pumax_p)(t_pumax v, t_p c);
typedef t_pumax	(*t_func_pumax_pumax_p)(t_pumax v, t_p c);
typedef t_uptr	*t_puptr;
typedef t_uptr	(*t_func_uptr_p)(void *context);
typedef t_uptr	*(*t_func_puptr_p)(void *context);
typedef t_uptr	(*t_func_uptr_uptr_p)(t_uptr v, t_p c);
typedef t_puptr	(*t_func_puptr_uptr_p)(t_uptr v, t_p c);
typedef t_uptr	(*t_func_uptr_puptr_p)(t_puptr v, t_p c);
typedef t_puptr	(*t_func_puptr_puptr_p)(t_puptr v, t_p c);
typedef t_p		*t_pp;
typedef t_p		(*t_func_p_p)(void *context);
typedef t_p		*(*t_func_pp_p)(void *context);
typedef t_p		(*t_func_p_p_p)(t_p v, t_p c);
typedef t_pp	(*t_func_pp_p_p)(t_p v, t_p c);
typedef t_p		(*t_func_p_pp_p)(t_pp v, t_p c);
typedef t_pp	(*t_func_pp_pp_p)(t_pp v, t_p c);
typedef t_err	*t_perr;
typedef t_err	(*t_func_err_p)(void *context);
typedef t_err	*(*t_func_perr_p)(void *context);
typedef t_err	(*t_func_err_err_p)(t_err v, t_p c);
typedef t_perr	(*t_func_perr_err_p)(t_err v, t_p c);
typedef t_err	(*t_func_err_perr_p)(t_perr v, t_p c);
typedef t_perr	(*t_func_perr_perr_p)(t_perr v, t_p c);
typedef t_byte	*t_pbyte;
typedef t_byte	(*t_func_byte_p)(void *context);
typedef t_byte	*(*t_func_pbyte_p)(void *context);
typedef t_byte	(*t_func_byte_byte_p)(t_byte v, t_p c);
typedef t_pbyte	(*t_func_pbyte_byte_p)(t_byte v, t_p c);
typedef t_byte	(*t_func_byte_pbyte_p)(t_pbyte v, t_p c);
typedef t_pbyte	(*t_func_pbyte_pbyte_p)(t_pbyte v, t_p c);

#endif
